export const examplePosts = [
  {
    id: 1,
    title: "Welcome to the blog!",
    content: "This is the first post on our new platform.",
    author: "Henry",
    createdAt: "2025-07-01T10:30:00Z",
  },
  {
    id: 2,
    title: "Exploring TypeScript Tips",
    content: "Today we'll cover some neat features in TypeScript.",
    author: "Ana",
    createdAt: "2025-07-02T14:15:00Z",
  },
  {
    id: 3,
    title: "Understanding REST APIs",
    content: "REST APIs follow a simple but powerful structure.",
    author: "Carlos",
    createdAt: "2025-07-03T11:00:00Z",
  },
  {
    id: 4,
    title: "10 VSCode Extensions You Need",
    content: "Boost productivity with these extensions.",
    author: "Henry",
    createdAt: "2025-07-04T08:45:00Z",
  },
  {
    id: 5,
    title: "Dockerizing Your Node.js App",
    content: "Learn how to containerize and deploy your backend.",
    author: "Lucía",
    createdAt: "2025-07-05T16:20:00Z",
  },
  {
    id: 6,
    title: "Authentication with JWT",
    content: "A step-by-step guide to secure your endpoints.",
    author: "Carlos",
    createdAt: "2025-07-06T13:10:00Z",
  },
  {
    id: 7,
    title: "Building with React & Tailwind",
    content: "How to design fast and responsive UIs.",
    author: "Ana",
    createdAt: "2025-07-07T09:30:00Z",
  },
  {
    id: 8,
    title: "Handling File Uploads in Express",
    content: "Best practices using Multer and validation.",
    author: "Henry",
    createdAt: "2025-07-08T15:55:00Z",
  },
  {
    id: 9,
    title: "PostgreSQL Tips for Beginners",
    content: "Use indexes, constraints, and more effectively.",
    author: "Lucía",
    createdAt: "2025-07-09T10:40:00Z",
  },
  {
    id: 10,
    title: "Intro to Prisma ORM",
    content: "Model your database with TypeScript and ease.",
    author: "Carlos",
    createdAt: "2025-07-10T17:25:00Z",
  },
];
